drift/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from rest_framework.authtoken import views as rf_views

from . import views
from . import api

app_name = 'drift'

urlpatterns = [
    path('', views.UserDashboardView.as_view(), name='home'),
    path('accounts/profile/', views.UserAccountView.as_view(), name='account'),
    path('accounts/register/', views.RegisterAccountView.as_view(), name='register'),
    path('accounts/register/<int:user_id>/', views.RegisterAccountView.as_view(), name='register'),
    path('accounts/changePassword/', views.ChangePasswordView.as_view(), name='changePassword'),
    path('activateEmail/<str:nonce>/', views.ActivateEmailView.as_view(), name='activateEmail'),
    path('events/', views.ListEventsView.as_view(), name='listEvents'),
    path('event/<int:pk>', views.EventView.as_view(), name='viewEvent'),
    path('teams/manufacturers/', views.ManufacturerTeamView.as_view(), name='listManufacturers'),
    path('teams/manufacturers/<str:teamName>/', views.ManufacturerTeamView.as_view(), name='showManufacturer'),
    path('teams/teams/', views.TeamView.as_view(), name='listTeams'),
    path('teams/teams/<str:teamName>/', views.TeamView.as_view(), name='showTeam'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('racers/', views.RacerListView.as_view(), name='listRacers'),
    path('racers/<int:pk>', views.RacerView.as_view(), name='viewRacer'),
    path('fantasyTeams', views.MyFantasyTeams.as_view(), name='myFantasyTeams'),
    path('fantasyTeams/teams/create/', views.CreateFantasyTeam.as_view(), name='createFantasyTeam'),
    path('fantasyTeams/teams/create/<int:league_id>/<str:key_code>/', views.CreateFantasyTeam.as_view(), name='createFantasyTeam'),
    path('fantasyTeams/teams/create/<int:league_id>/', views.CreateFantasyTeam.as_view(), name='createFantasyTeam'),
    path('fantasyTeams/teams/edit/<int:team_id>', views.CreateFantasyTeam.as_view(), name='editFantasyTeam'),
    path('fantasyTeams/teams/<int:team_id>', views.ViewFantasyTeam.as_view(), name='viewFantasyTeam'),
    path('fantasyTeams/teams/<int:team_id>/<int:event_id>', views.ViewFantasyTeam.as_view(), name='viewFantasyTeam'),
    path('fantasyTeams/teams/sendMessage/<int:team_id>/', views.MessageOtherTeam.as_view(), name='sendMessage'),
    path('fantasyTeams/teams/sendMessage/<int:team_id>/<int:sendTo>/', views.MessageOtherTeam.as_view(), name='sendMessage'),
    path('leagues/', views.AllLeagues.as_view(), name='allLeagues'),
    path('leagues/<int:pk>/', views.LeagueView.as_view(), name='league'),
    path('leagues/create/', views.CreateLeagueView.as_view(), name='createLeague'),
    path('leagues/create/<int:league_id>/', views.CreateLeagueView.as_view(), name='createLeague'),
    path('leagues/createScoring/<int:league_id>/', views.CreateLeagueScoringView.as_view(), name='createLeagueScoring'),
    path('leagues/invite/<int:league_id>/', views.InviteUsersToJoinLeague.as_view(), name='inviteToJoinLeague'),
    path('leagues/acquire/<int:league_id>/', views.AcquireDriver.as_view(), name='acquireDriver'),
    path('leagues/acquire/waive/<int:driver_id>/<int:team_id>/', views.AddDriverToWaiverWire.as_view(), name='waiveDriver'),
    path('leagues/trade/<int:team_id>/', views.TradeView.as_view(), name='trade'),
    path('leagues/trade/<int:team_id>/<int:racer_id>/', views.TradeView.as_view(), name='trade'),
    path('leagues/trade/decideTrade/<int:trade_id>/<str:accept>/', views.AcceptTradeView.as_view(), name='decideTrade'),
    path('draft/<int:team_id>/', views.DraftView.as_view(), name='draft'),
    path('api/event/', api.EventApi.as_view(), name='addEvent'),
    path('api/race/', api.RaceApi.as_view(), name='addRace'),
    path('api/racer/', api.RacerApi.as_view(), name='addRacer'),
    path('api/ranking/', api.RankingApi.as_view(), name='addRanking'),
    path('api/qualify/', api.QualifyApi.as_view(), name='addQualify'),
    path('api/activate/', api.ActivateDriverApi.as_view(), name='activateDriver'),
    path('api/getPoints/<int:event>/<int:team>/<int:racer>', api.PointsApi.as_view(), name='points'),
    path('api/checkWaiverWire/', api.CheckWaiverWire.as_view(), name='checkWaiverWire'),
    path('api/draft/pick/<int:team_id>/', api.DraftPickAPI.as_view(), name='draftPick'),
    path('api/queue/<int:team_id>/', api.QueueAPI.as_view(), name='queue'),
    path('api/queue/<int:team_id>/<int:racer_id>/', api.QueueAPI.as_view(), name='queue'),
    path('api/queue/<int:team_id>/<int:racer_id>/<str:position>/', api.QueueAPI.as_view(), name='queue'),
    path('api/notification/<str:lastPoll>/', api.NotificationApi.as_view(), name='notification'),
    path('api/token-auth/', rf_views.obtain_auth_token),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')), name='favicon'),
]

fdfantasy/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('drift.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('docs/', include_docs_urls(title='My API service'), name='api-docs'),
]

drift/forms.py
from django import forms

from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from drift.models import *


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class EditAccountForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', )

class LeagueForm(forms.ModelForm):
    name = forms.CharField(max_length=30, required=True, help_text='Required')
    class Meta:
        model = League
        fields = ['name', 'key_required']

class DateInput(forms.DateInput):
    input_type = 'date'

class DraftDateForm(forms.ModelForm):
    draft = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget, required=True, help_text='Required, use YYYY-MM-DD and HH:MM')
    class Meta:
        model = DraftDate
        fields = ['draft']

class TeamForm(forms.ModelForm):
    name = forms.CharField(max_length=30, required=True, help_text='Required')
    key_code = forms.CharField(max_length=32, required=False, help_text='Required. Check email.')
    class Meta:
        model = Team
        fields = ['league', 'key_code', 'name']

class InviteUserForm(forms.ModelForm):
    email = forms.CharField(max_length=30, required=True, help_text='Required')
    class Meta:
        model = LeagueInvite
        fields = ['email']

class MessageTeamForm(forms.ModelForm):

    class Meta:
        model = Notification
        fields = ['user', 'msg']

class TradeForm(forms.ModelForm):
    deadline = forms.SplitDateTimeField(widget=forms.SplitDateTimeWidget, required=True, help_text='Required, use YYYY-MM-DD and HH:MM')

    class Meta:
        model = Trade
        fields = ['deadline']

drift/views.py
import random
import hashlib
import time
from collections import OrderedDict

from huey.contrib.djhuey import HUEY

from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm
from django.core.mail import send_mail

from django.db.models import Sum
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import render
from django_tables2 import RequestConfig
from django.template import Context
from django.template.loader import get_template
from django.utils import timezone
from django.urls import reverse
from django.views import View
from django.contrib.auth import authenticate, login
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied

# Create your views here.
from django.conf import settings
from drift.models import *
from drift.forms import *
from drift.tables import *
from drift.api import *

class ActivateEmailView(View):

    def get(self, request, nonce):
        d = UserDetail.objects.filter(nonce=nonce)[0]
        d.activated = True
        d.save()
        return HttpResponseRedirect(reverse('drift:home'))

class RegisterAccountView(View):

    def post(self, request, user_id=None):
        '''need to post data'''

        if user_id is not None:
            user = User.objects.get(id=user_id)
            signUpForm = EditAccountForm(request.POST, instance=user)
            edit = True
        else:
            edit = False
            signUpForm = SignUpForm(request.POST)

        if signUpForm.is_valid():
            if edit:
                print(signUpForm)
                user = signUpForm.save()
                return HttpResponseRedirect(reverse('drift:account'))
            else:
                matchingEmail = User.objects.filter(email=signUpForm.cleaned_data['email'])
                if len(matchingEmail) > 0:
                    signUpForm.add_error(None, "A user with that email already exists")
                
                if len(matchingEmail) == 0:
                    user = signUpForm.save()
                    ud = UserDetail.objects.create(user=user, nonce=int(random.uniform(1000000000, 10000000000000000)))
                    ud.save()

                    if not edit:

                        new_user = authenticate(
                            username=signUpForm.cleaned_data['username'],
                            password=signUpForm.cleaned_data['password1'],
                            )
                        login(request, new_user)
                        adminUser = User.objects.filter(username='admin')[0]
                        email_msg = get_template(
                            'drift/email_activateEmail.html'
                            ).render({
                                'nonce': ud.nonce,
                                'user': request.user,
                                'baseUrl': settings.ROOT_URL
                                })
                        send_mail(
                            "FD Fantasy Activation",
                            email_msg,
                            settings.DEFAULT_FROM_EMAIL,
                            [new_user.email]
                            )
                        note = Notification.objects.create(
                            user=new_user,
                            sender=adminUser,
                            msg='Welcome to FD Fantasy!'
                        )
                        note.save()
                    return HttpResponseRedirect(reverse('drift:home'))

        context = {
            'signUpForm': signUpForm,
            }

        return render(request, 'drift/register.html', context=context)

    def get(self, request, user_id=None):

        form = SignUpForm()
        if request.user.is_authenticated:
            user = User.objects.get(id=user_id)
            if user == request.user:
                form = EditAccountForm(None, instance=user)

        context = {
            'signUpForm': form,
            }

        return render(request, 'drift/register.html', context=context)

class ChangePasswordView(View):
    def post(self, request):
        '''need to post data'''

        form = PasswordChangeForm(request.user, request.POST)

        if form.is_valid():
            change = form.save()
            return HttpResponseRedirect(reverse('drift:home'))

        context = {}
        context['form'] = PasswordChangeForm(user=request.user)
        return render(request, 'drift/changePassword.html', context=context)

    def get(self, request):
        form = PasswordChangeForm(user=request.user)

        context = {'form': form}

        return render(request, 'drift/changePassword.html', context=context)
    

class UpcomingEvent(object):

    def __init__(self, title, date, url=None):
        self.title = title
        self.date = date
        self.url = url

def getUpcoming(user):
    timeNow = timezone.now()
    eventLi = []
    teams = Team.objects.filter(owner=user)
    leagues = set([x.league for x in teams])

    draft = [x.draftdate for x in leagues if x.draftdate.draft >= timeNow]
    draft = [
        UpcomingEvent(
            'Draft',
            x.draft,
            reverse('drift:league', args=[x.league.id])
            ) for x in draft
        ]
    eventLi.extend(draft)

    races = Event.objects.filter(end__gte=timeNow).order_by('start')
    if len(races) > 0:
        races = races[0:min([len(races), 3])]
        races = [
            UpcomingEvent(
                x.name,
                x.start,
                reverse('drift:viewEvent', args=[x.id])
                ) for x in races
            ]
        eventLi.extend(races)

    return eventLi

class UserDashboardView(View):

    def get(self, request):
        """Need to return some general links"""

        if request.user.is_authenticated:

            teams = Team.objects.filter(owner=request.user.id)

            leagues = set([t.league for t in teams])
            upcoming = getUpcoming(request.user)
            notifications = Notification.objects.filter(
                user=request.user
                ).order_by('-created_at')

            context = {
                'teams': teams,
                'leagues': leagues,
                'upcoming': upcoming,
                'notifications': notifications,
            }

        else:
            context = {'form': AuthenticationForm}

        return render(request, 'drift/userDashboard.html', context=context)

class AllLeagues(View):

    def get(self, request):
        leagues = League.objects.all()

        try:
            myLeague = request.user.league_set.all()
        except:
            myLeague = None

        try:
            myTeams = request.user.team_set.all()
            myTeamsDic = {}
            for team in myTeams:
                if team.league.name not in myTeamsDic.keys():
                    myTeamsDic[team.league.name] = team
            myTeams = [val for key,val in myTeamsDic.items()]
        except:
            myTeams = None

        context = {
            'leagues': leagues,
            'myLeagues': myLeague,
            'myTeams': myTeams
        }

        return render(request, 'drift/leagues.html', context=context)

def draftInFuture(league):
    return timezone.now() < league.draftdate.draft


class CreateLeagueView(View):

    def post(self, request, league_id=None):
        """Save new or updated league"""

        active_season = Season.objects.filter(active=True).latest('end')

        if league_id is not None:
            league = League.objects.get(id=league_id)
            form1 = LeagueForm(request.POST, instance=league)
            form2 = DraftDateForm(request.POST, instance=league.draftdate)

        else:
            form1 = LeagueForm(request.POST)
            form2 = DraftDateForm(request.POST)
        if form1.is_valid():
            if form2.is_valid():
                if form2.cleaned_data['draft'] >= timezone.now():
                    league = form1.save(commit=False)
                    league.race_official = request.user
                    league.season = active_season
                    league.save()
                    
                    draft = form2.save(commit=False)
                    draft.league = league
                    draft.save()
                    return HttpResponseRedirect(reverse('drift:createLeagueScoring', args=[league.id]))
                else:
                    form2.add_error(None, 'Draft must be in future')
        context = {'leagueForm': form1, 'draftForm': form2}
        return render(request, 'drift/createLeague.html', context=context)

    def get(self, request, league_id=None):
        if league_id is not None:
            league = League.objects.get(id=league_id)
            form1 = LeagueForm(None, instance=league)
            form2 = DraftDateForm(None, instance=league.draftdate)

        else:
            form1 = LeagueForm()
            form2 = DraftDateForm()

        context = {'leagueForm': form1, 'draftForm': form2}

        return render(request, 'drift/createLeague.html', context=context)

class CreateLeagueScoringView(View):

    def post(self, request, league_id):
        """Save new or updated league"""

        active_season = Season.objects.filter(active=True).latest('end')

        league = League.objects.get(id=league_id)
        if request.user != league.race_official:
            raise PermissionDenied
        ##Get from post
        vals = []
        invalidList = []
        for x in ScoringValue.AWARDS:
            test = request.POST[x[0]]
            if not isinstance(test, int) or isinstance(test, float):
                invalidList.append(x[0])
                vals.append([x[0], ScoringValue.DEFAULTS[x[0]]])
        print(invalidList)

        ##TODO: Check for validity
        if invalidList != []:
            for x in ScoringValue.AWARDS:
                temp = request.POST[x[0]]

drift/templates/drift/about.html
{% extends "base.html" %}

{% block title %} About {% endblock title %}

{% block title_page %}
    <h3>About</h3>
{% endblock title_page %}

{% block content %}
    <p>Welcome to this beta Formula Drift fantasy website for building virtual teams and competing against your friends.</p>
    
{% endblock content %}

drift/templates/drift/createInvites.html
{% extends "base.html" %}

{% block title %} send Invite for League {% endblock title %}

{% block title_page %}
    <h3>Send Invite to Join {{league.name}}</h3>
{% endblock title_page %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send Invite">
    </form>

{% endblock content %}

{% block javascript_footer %}

{% endblock %}

drift/templates/drift/draftBoardToEarly.html
{% extends "base.html" %}

{% block title %} Draft - {{team.league.name}} {% endblock title %}

{% block title_page %}
    
{% endblock title_page %}

{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Draft Not Started!</h3>
                </div>
                <div class="panel-body">
                    <p>You are too early for your draft! The draft board will open 1 hour before your leagues scheduled draft date and time.</p>
                    <p>Draft starts at: {{team.league.draftdate.draft}}</p>
                    <p>You have {{team.league.draftdate.draft|timeuntil}} until your draft starts.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

drift/templates/drift/email_activateEmail.html
Welcome to fdfantasy.com {{user.username}}!

Thank you for joining! We would like to validate your email for maximum use of the site. Please click on or paste into your browser http://{{baseUrl}}{% url 'drift:activateEmail' nonce %} to validate this email address belongs to you.

Best,
The FD Fantasy team

drift/templates/drift/email_draftStarting.html
Your draft for your team {{team.name}} is starting now! <a href="http://{{baseUrl}}{% url 'drift:draft' team.id %}">Click here</a> to join the draft in progress, otherwise your automatic draft order will take your highest priority drivers.

Good luck!
The FD Fantasy team

drift/templates/drift/email_draftStartingSoon.html
Your draft for your team {{team.name}} is starting in {{team.league.draftdate.draft|timeuntil}}! <a href="http://{{baseUrl}}{% url 'drift:draft' team.id %}">Click here</a> to join the draft before (or after) it starts and to make sure that everything is working. In case you are unable to join, your automatic draft order will take your highest priority drivers.

Good luck!
The FD Fantasy team

drift/templates/drift/email_driverAdded.html
Congratulations, you acquired {{racer.name}} and they can now be activated for your next event.

{% if waiver and waiver.waiverwireremove_set.all|length > 0 %}
    You dropped {{waiver.waiverwireremove_set.all}}.
{% endif %}

Best,
The FD Fantasy team

drift/templates/drift/email_driverAddedToWaiver.html
You added {{racer.name}} to the waiver wire. Your waiver priority is {{team.waiverpriority.getLeagueOrderRank}} of {{team.waiverpriority.getLeagueOrder|length}}. Once {{team.league.waiver_hours}} hours pass, if the driver has not been selected by a higher priority team, they will be added to your team automatically and you will receive another notification.

Best,
The FD Fantasy team

drift/templates/drift/email_sendMessage.html
You have received a message from a team in your league:

{{note.msg}}

Best,
{{note.sender}}

drift/templates/drift/email_tradeDecision.html
{{note.msg}}

Best,
The FD Fantasy team

drift/templates/drift/email_tradeProposed.html
User {{trade.proposer.owner.username}} has proposed a trade: {{trade.tradeDescription}}.

Please visit http://{{baseUrl}}{% url 'drift:trade' trade.proposedTo.id %}.

Best,
The FD Fantasy team

drift/templates/drift/racersList.html
{% extends "base.html" %}

{% block title %} Driver List {% endblock title %}

{% block title_page %}
    <h3>Driver List</h3>
{% endblock title_page %}

{% block content %}

    <table class="table">
        <thead><td>Driver</td><td>Team</td><td>Number</td><td>Manufacturer</td><td>Class</td><td>FD Bio</td></thead>
        {% for driver in drivers %}
            <tr>
                <td><a href="{% url 'drift:viewRacer' driver.id %}">{{driver.name}}</a></td>
                <td>{{driver.team_name}}</td>
                <td>{{driver.car_number}}</td>
                <td>{{driver.car_manuf}}</td>
                <td>{% if driver.pro2 == True %} Pro2 {% else %} Pro {% endif %}</td>
                <td><a href="https://formulad.com/{{driver.driver_url_slug}}">FD Bio</a></a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

drift/templates/drift/viewTeam.html
{% extends "base.html" %}
{% load render_table from django_tables2 %}

{% block title %} Team - {{team.name}} {% endblock title %}

{% block title_page %}
    <h3>{{team.name}}</h3>
{% endblock title_page %}

{% block content %}

    <div class="row">
        <div class="col-sm-12">
            <p>League: <a href="{% url 'drift:league' team.league.id %}">{{team.league.name}}</a></p>
            {% if nextEvent != None %}
                <p>Next event: <a href="{% url 'drift:viewEvent' nextEvent.id %}">{{nextEvent.name}} ({{nextEvent.start}} - {{nextEvent.end}})</a></p>        
            {% endif %}
            {% if draftInFuture %}
                <p>Draft: {{team.league.draftdate.draft}} ({{team.league.draftdate.draft|timeuntil}})</p>
                <p><em>The draft is each team's opportunity to select racers for the season. While a team can acquire drivers via trades and free agency, this is the opportunity for teams to acquire most of their talent. Make sure to participate in your league's draft. More details coming soon!</em></p>
            {% endif %}
            {% if request.user == team.owner and not draftInFuture %}
                <p><a href="{% url 'drift:acquireDriver' team.league.id %}">Add Racers from Free Agency</a></p>
                <p><a href="{% url 'drift:trade' team.id %}">Trade Dashboard</a></p>
            {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            {% for topEvent in events %}
                {% if topEvent.end <= nextEvent.end %}
                    <a href="{% url 'drift:viewFantasyTeam' team.id topEvent.id %}">
                        {% if topEvent.end == nextEvent.end %}
                            <button type="button" class="btn btn-success">
                        {% else %}
                            <button type="button" class="btn btn-info">
                        {% endif %}
                            {{topEvent.start}}
                        </button>
                    </a>
                {% else %}
                    <a href="{% url 'drift:viewFantasyTeam' team.id %}">
                        <button type="button" class="btn btn-light">
                            {{topEvent.start}}
                        </button>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
        <h4>Active</h4>
            <p><em>Active drivers count toward the next event's score. Once the event starts (i.e. the day of), the lineup will be locked.</em></p>
            {% if active|length == 0 %}
                <li>There are no active drivers. If you have drivers on your team, click the "activate" button to move them into this slot.</li>
            {% else %}
                <table class='table'>
                    <thead><th style="width: 21%"></th><th style="width: 50%">Racer</th><th>Pro2</th>{% for x in scoringValHeaders %}<th>{{x}}</th>{% endfor %}<th>this event</th>{% for x in scoringValHeaders %}<th>{{x}}</th>{% endfor %}<th>all</th></thead>
                    <tbody>
                        {% for racer in active %}
                            <tr>
                                <td>
                                    {% if owner %}
                                        <form id="deactivateForm" action="{% url 'drift:activateDriver' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" id="team" name="team" value="{{team.id}}">
                                            <input type="hidden" id="racer" name="racer" value="{{racer.id}}">
                                            <input type="hidden" id="status" name="status" value="False"}}>
                                            <button type="button" class="btn btn-outline-danger" name="submitButton" active="{{owner}}">Deactivate</button>
                                        </form>
                                    {% endif %}
                                </td>

                                <td><a href="{% url 'drift:viewRacer' racer.id %}">{{racer.racer.name}}</a></td>
                                
                                <td>{% if racer.racer.pro2 %}<span class="glyphicon glyphicon-ok"></span>{% else %}<span class="glyphicon glyphicon-minus-sign"></span>{% endif %}</td>
                                {% for pt in racer.eventPointsLi %}
                                    <td>{{pt}}</td>
                                {% endfor %}
                                <td>{{racer.eventPoints}}</td>
                                {% for pt in racer.allPointsLi %}
                                    <td>{{pt}}</td>
                                {% endfor %}
                                <td>{{racer.allPoints}}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td>TOTAL</td>
                            <td></td>
                            {% for x in scoringValHeaders %}<td></td>{% endfor %}
                            <td>{{totalPoints.active.eventPoints}}</td>
                            {% for x in scoringValHeaders %}<td></td>{% endfor %}
                            <td>{{totalPoints.active.allPoints}}</td>
                        </tr>
                    </tbody>
                </table>
            {% endif %}

        <h4>Inactive</h4>
            <p><em>Inactive drivers do not count toward an event's score. To move a driver to "inactive" click "Deactivate" from your list of active drivers.</em></p>
            {% if inactive|length == 0 %}
                <li>There are no inactive drivers</li>
            {% else %}
                <table class="table">
                    <thead><th style="width: 21%"></th><th style="width: 50%">Racer</th><th>Pro2</th>{% for x in scoringValHeaders %}<th>{{x}}</th>{% endfor %}<th>this event</th>{% for x in scoringValHeaders %}<th>{{x}}</th>{% endfor %}<th>all</th></thead>
                    <tbody>
                    {% for racer in inactive %}
                        <tr>
                            <td>
                                {% if owner %}
                                    <form id="activateForm" action="{% url 'drift:activateDriver' %}" method="post">
                                        {% csrf_token %}
                                        <input type="hidden" id="team" name="team" value="{{team.id}}">
                                        <input type="hidden" id="racer" name="racer" value="{{racer.id}}">
                                        <input type="hidden" id="status" name="status" value="True"}}>
                                        <button type="button" class="btn btn-outline-success" name="submitButton">Activate</button>
                                    </form>
                                {% endif %}
                            </td>
                            <td><a href="{% url 'drift:viewRacer' racer.id %}">{{racer.racer.name}}</a></td>
                            <td>{% if racer.racer.pro2 %}<span class="glyphicon glyphicon-ok"></span>{% else %}<span class="glyphicon glyphicon-minus-sign"></span>{% endif %}</td>
                            {% for pt in racer.eventPointsLi %}
                                <td>{{pt}}</td>
                            {% endfor %}
                            <td>{{racer.eventPoints}}</td>
                            {% for pt in racer.allPointsLi %}
                                <td>{{pt}}</td>
                            {% endfor %}
                            <td>{{racer.allPoints}}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td></td>
                        <td>TOTAL</td>
                        <td></td>
                        {% for x in scoringValHeaders %}<td></td>{% endfor %}
                        <td>{{totalPoints.inactive.eventPoints}}</td>
                        {% for x in scoringValHeaders %}<td></td>{% endfor %}
                        <td>{{totalPoints.inactive.allPoints}}</td>
                    </tr>
                    </tbody>
                </table>
            {% endif %}
        </div>
    </div>

{% endblock content %}

{% block javascript_footer %}

    $('button[name="submitButton"]').click(function(e) {

        e.preventDefault(); // avoid to execute the actual submit of the form.
    
        var form = $(this).closest("form");
        var url = form.attr('action');
        var data = form.serialize();
    
        $.ajax({
               type: "POST",
               url: url,
               data: data, // serializes the form's elements.
               success: function(data)
               {
                    window.location.reload();
                    alert(data['msg']);
               }
             });
    });

{% endblock %}