drift/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from rest_framework.authtoken import views as rf_views

from . import views
from . import api

app_name = 'drift'

urlpatterns = [
    path('', views.UserDashboardView.as_view(), name='home'),
    path('accounts/profile/', views.UserAccountView.as_view(), name='account'),
    path('accounts/register/', views.RegisterAccountView.as_view(), name='register'),
    path('accounts/register/<int:user_id>/', views.RegisterAccountView.as_view(), name='register'),
    path('accounts/changePassword/', views.ChangePasswordView.as_view(), name='changePassword'),
    path('activateEmail/<str:nonce>/', views.ActivateEmailView.as_view(), name='activateEmail'),
    path('events/', views.ListEventsView.as_view(), name='listEvents'),
    path('event/<int:pk>', views.EventView.as_view(), name='viewEvent'),
    path('teams/manufacturers/', views.ManufacturerTeamView.as_view(), name='listManufacturers'),
    path('teams/manufacturers/<str:teamName>/', views.ManufacturerTeamView.as_view(), name='showManufacturer'),
    path('teams/teams/', views.TeamView.as_view(), name='listTeams'),
    path('teams/teams/<str:teamName>/', views.TeamView.as_view(), name='showTeam'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('racers/', views.RacerListView.as_view(), name='listRacers'),
    path('racers/<int:pk>', views.RacerView.as_view(), name='viewRacer'),
    path('fantasyTeams', views.MyFantasyTeams.as_view(), name='myFantasyTeams'),
    path('fantasyTeams/teams/create/', views.CreateFantasyTeam.as_view(), name='createFantasyTeam'),
    path('fantasyTeams/teams/create/<int:league_id>/<str:key_code>/', views.CreateFantasyTeam.as_view(), name='createFantasyTeam'),
    path('fantasyTeams/teams/create/<int:league_id>/', views.CreateFantasyTeam.as_view(), name='createFantasyTeam'),
    path('fantasyTeams/teams/edit/<int:team_id>', views.CreateFantasyTeam.as_view(), name='editFantasyTeam'),
    path('fantasyTeams/teams/<int:team_id>', views.ViewFantasyTeam.as_view(), name='viewFantasyTeam'),
    path('fantasyTeams/teams/<int:team_id>/<int:event_id>', views.ViewFantasyTeam.as_view(), name='viewFantasyTeam'),
    path('fantasyTeams/teams/sendMessage/<int:team_id>/', views.MessageOtherTeam.as_view(), name='sendMessage'),
    path('fantasyTeams/teams/sendMessage/<int:team_id>/<int:sendTo>/', views.MessageOtherTeam.as_view(), name='sendMessage'),
    path('leagues/', views.AllLeagues.as_view(), name='allLeagues'),
    path('leagues/<int:pk>/', views.LeagueView.as_view(), name='league'),
    path('leagues/create/', views.CreateLeagueView.as_view(), name='createLeague'),
    path('leagues/create/<int:league_id>/', views.CreateLeagueView.as_view(), name='createLeague'),
    path('leagues/createScoring/<int:league_id>/', views.CreateLeagueScoringView.as_view(), name='createLeagueScoring'),
    path('leagues/invite/<int:league_id>/', views.InviteUsersToJoinLeague.as_view(), name='inviteToJoinLeague'),
    path('leagues/acquire/<int:league_id>/', views.AcquireDriver.as_view(), name='acquireDriver'),
    path('leagues/acquire/waive/<int:driver_id>/<int:team_id>/', views.AddDriverToWaiverWire.as_view(), name='waiveDriver'),
    path('leagues/trade/<int:team_id>/', views.TradeView.as_view(), name='trade'),
    path('leagues/trade/<int:team_id>/<int:racer_id>/', views.TradeView.as_view(), name='trade'),
    path('leagues/trade/decideTrade/<int:trade_id>/<str:accept>/', views.AcceptTradeView.as_view(), name='decideTrade'),
    path('draft/<int:team_id>/', views.DraftView.as_view(), name='draft'),
    path('api/event/', api.EventApi.as_view(), name='addEvent'),
    path('api/race/', api.RaceApi.as_view(), name='addRace'),
    path('api/racer/', api.RacerApi.as_view(), name='addRacer'),
    path('api/ranking/', api.RankingApi.as_view(), name='addRanking'),
    path('api/qualify/', api.QualifyApi.as_view(), name='addQualify'),
    path('api/activate/', api.ActivateDriverApi.as_view(), name='activateDriver'),
    path('api/getPoints/<int:event>/<int:team>/<int:racer>', api.PointsApi.as_view(), name='points'),
    path('api/checkWaiverWire/', api.CheckWaiverWire.as_view(), name='checkWaiverWire'),
    path('api/draft/pick/<int:team_id>/', api.DraftPickAPI.as_view(), name='draftPick'),
    path('api/queue/<int:team_id>/', api.QueueAPI.as_view(), name='queue'),
    path('api/queue/<int:team_id>/<int:racer_id>/', api.QueueAPI.as_view(), name='queue'),
    path('api/queue/<int:team_id>/<int:racer_id>/<str:position>/', api.QueueAPI.as_view(), name='queue'),
    path('api/notification/<str:lastPoll>/', api.NotificationApi.as_view(), name='notification'),
    path('api/token-auth/', rf_views.obtain_auth_token),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')), name='favicon'),
]

fdfantasy/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from rest_framework.documentation import include_docs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('drift.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('docs/', include_docs_urls(title='My API service'), name='api-docs'),
]

templates/base.html
{% load static %}
{% load render_table from django_tables2 %}
<html>
    <head>
        <title>{% block title %} {% endblock title %}</title>
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="Formulat Drift Fantasy website.">
		<meta name="author" content="Jarrod Olson">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
        <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
        <script src="{% static 'rest_framework/js/coreapi-0.1.1.js' %}"></script>
        <script src="{% url 'api-docs:schema-js' %}"></script>
    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false" aria-controls="navbar">
                    <span class="glyphicon glyphicon-th" aria-hidden="true">

                </button>
                <!--<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#user-navbar-collapse" aria-expanded="true" aria-controls="navbar">-->
                    <!--<span class="glyphicon glyphicon-user" aria-hidden="true">-->
                <!--</button>-->
                <a class="navbar-brand" href="{% url 'drift:home' %}">FD Fantasy</a>
                </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="main-navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'drift:myFantasyTeams' %}">My Teams</a></li>
                    <li><a href="{% url 'drift:listEvents' %}">Events</a></li>
                    <li><a href="{% url 'drift:listRacers' %}">Drivers</a></li>
                    <li><a href="{% url 'drift:about' %}">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">Manage <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <!--<li role="separator" class="divider"></li>-->
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'drift:account' %}">Account</a></li>
                            <li><a href="{% url 'logout' %}">Log Out</a></li>
                        {% else %}
                            <li><a href="{% url 'login' %}">Log In</a></li>
                        {% endif %}
                    </ul>
                    </li>
                </ul>
                </div><!-- /.navbar-collapse -->
            </div>
            </nav>

        <div class="content container">
            {% block title_page %} {% endblock title_page %}
            {% block content %} {% endblock content %}
        </div>
    </body>
    <scripts>
        <script src="{% static 'bootstrap.min.js' %}" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
        <script>
            $(function() {
                var pull 		= $('#pull');
                    menu 		= $('nav ul');
                    menuHeight	= menu.height();

                $(pull).on('click', function(e) {
                    e.preventDefault();
                    menu.slideToggle();
                });

                $(window).resize(function(){
                    var w = $(window).width();
                    if(w > 320 && menu.is(':hidden')) {
                        menu.removeAttr('style');
                    }
                });
            });
            
            $.fn.serializeObject = function() {
                var o = {};
                //var a = this.serializeArray();
                $(this).find('input[type="hidden"], input[type="text"], input[type="password"], input[type="checkbox"]:checked, input[type="radio"]:checked, select').each(function() {
                    if ($(this).attr('type') == 'hidden') { //If checkbox is checked do not take the hidden field
                        var $parent = $(this).parent();
                        var $chb = $parent.find('input[type="checkbox"][name="' + this.name.replace(/\[/g, '\[').replace(/\]/g, '\]') + '"]');
                        if ($chb != null) {
                            if ($chb.prop('checked')) return;
                        }
                    }
                    if (this.name === null || this.name === undefined || this.name === '')
                        return;
                    var elemValue = null;
                    if ($(this).is('select'))
                        elemValue = $(this).find('option:selected').val();
                    else
                        elemValue = this.value;
                    if (o[this.name] !== undefined) {
                        if (!o[this.name].push) {
                            o[this.name] = [o[this.name]];
                        }
                        o[this.name].push(elemValue || '');
                    }
                    else {
                        o[this.name] = elemValue || '';
                    }
                });
                return o;
            }
        </script>
        <script>
            const coreapi = window.coreapi;
            const schema = window.schema;
            let auth = new coreapi.auth.SessionAuthentication({
                csrfCookieName: 'csrftoken',
                csrfHeaderName: 'X-CSRFToken',
            });
            let client = new coreapi.Client({auth: auth});
            {% block javascript_footer %} {% endblock javascript_footer %}
        </script>
        

    </scripts>
</html>